### ISSUE TITLE
URL query parameters from plugins

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/fps#23]
Is it possible for a plugin to pass parameters back to FPS, so that these parameters appear as query parameters in the URL when the application is launched with `--open-browser`? The use-case I'm thinking of is when jupyverse is launched with token authentication: it should pass this token in the URL.

**Comment by adriendelsalle** [comment]
Let me think a bit about this!

**Comment by davidbrochart** [comment]
Done in #72.
