### ISSUE TITLE
Expose FastAPI app or allow registering exception handlers

### ISSUE THREAD

**Issue by hbcarlos** [jupyter-server/fps#27]
### Problem

Working on jupyverse, I need to register an exception handler to be able to redirect from a dependency see https://github.com/tiangolo/fastapi/issues/1039#issuecomment-591661667.
To register an exception handler we need access to the FastAPI app.

```
class RequiresLoginException(Exception):
    pass

@app.exception_handler(RequiresLoginException)
async def exception_handler(request: Request, exc: RequiresLoginException) -> Response:
    return RedirectResponse(url='/login')
```

### Proposed Solution
Exposing the app, or allowing to register new exception handlers.

### Additional context

I can try to open a PR but I need some help. I'm not sure what's the best way to proceed or how to implement it.

**Comment by adriendelsalle** [comment]
https://github.com/tiangolo/fastapi/issues/1667

**Comment by wolfv** [comment]
Wouldn't it make sense to have a exception handler in fps directly and then throw that specific exception from the plugins?

E.g.

```
from fps.exceptions import RedirectException

...

raise RedirectException(reason="Need to authenticate", redirect_to="/login")
...

```

**Comment by wolfv** [comment]
Ok, to elaborate what I meant:

FPS could have some "Behaviourial exceptions" such as a `RedirectException`:

File: `fps.exceptions`

```
class RedirectException(Exception):
   def __init__(self, reason, redirect_to):
        self.reason = reason
        self.redirect_to = redirect_to
```

Then fps could install the exception handler on the app:

File: `fps` wherever `app` is available:

```
...

@app.exception_handler(RedirectException)
async def exception_handler(request: Request, exc: RedirectException) -> Response:
    logger.log(f"Redirect: {exc.redirect_to}, reason: {exc.reason}")
    return RedirectResponse(url=exc.redirect_to)
```
