### ISSUE TITLE
Improve enabled/disabled plugins config

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/fps#40]
## Description

The first plugin given to `--fps.disabled_plugins` is not disabled.

## Reproduce

1. `pip install jupyverse`
2. Launch `jupyverse --fps.disabled_plugins=[authenticator,contents,kernels,Lab,nbconvert,terminals,yjs]`
3. Open a browser at `http://127.0.0.1/docs`
4. The `authenticator` plugin's endpoints are visible.

**Comment by davidbrochart** [comment]
Thanks!

**Comment by adriendelsalle** [comment]
in that case it's pretty annoying because default value will always be empty list (because `FPS` doesn't know about installed plugins), then you would always need to configure `enabled_plugins` to use them
