### ISSUE TITLE
Support file log handler

### ISSUE THREAD

**Issue by Wh1isper** [jupyter-server/fps#87]
### Problem

There seems to be no way to configure a logger with filehandler

I saw some code here https://github.com/jupyter-server/fps/blob/main/fps/logging.py#L189, and perhaps we should let the user configure handlers and give the optional handlers

### Proposed Solution

 support configure a logger with filehandler

### Additional context

Once user-configurable filehandler is supported, perhaps also consider how to allow users to customize the location of log files

**Comment by davidbrochart** [comment]
That would be a nice improvement @Wh1isper, do you want to open a PR?
